### ISSUE TITLE
Proxy check

### ISSUE THREAD

**Issue by 9point6** [bbc/morph-doctor#7]
https://github.com/bbc/morph-doctor/blob/master/lib/clinics/reith.ts

I realise this is not an ideal time for testing it, but does this work with zscaler proxies too?

**Comment by benwainwright** [comment]
Wow; good question. In fact - zscaler has rendered some of this redundant. Will probably need to check if we are on zscaler first before looking for env vars. Don't need them if it is on zscaler...

**Comment by benwainwright** [comment]
Originally I was going to suggest downgrading to a warning and changing the error message to make it clear that you don't need to do anything if you are on Zscaler. Turns out nothing needs to be done:

Zscaler doesn't appear to change the way the system DNS is configured, which is what I'm using to detect connection to the Reith network in the first place. So connection to Reith via Zscaler doesn't trigger an error here anyway.
